### ISSUE TITLE
PDF header design

### ISSUE THREAD

**Issue by agahkarakuzu** [brainhack-proceedings/brainhack-proceedings.github.io#1]
PDFs rendered by [this repo](https://github.com/Brainhack-Proceedings-2015/Craddock-AMX-Centrality) have the following header design:

![image](https://user-images.githubusercontent.com/9632322/80967703-c8413d00-8de4-11ea-83fe-eecf97ef5f1a.png)

I can work on a new design to indicate which year do they belong or omit this from the PDF, if the template  iframing  the PDF is going to contain the header.

**Comment by lunebellec** [comment]
@agahkarakuzu I am thinking about having the pdf displayed like this: https://psyarxiv.com/3epws
The entire page would be an iframe, except for the header on top, which is quite slim.
But we could have a header in the paper, and it would be cool to have the year in there as well. 

This header could also be used on the main page, but I would not include the year in there.
We would likely just have a tag to browse, e.g. all 2020 proceedings.

**Comment by lunebellec** [comment]
I find that the brainhack logo lends itself well to different color palettes (purple, yellow, etc). This is what I use for logos of the different teams. We could simply change the color palette for every year.

**Comment by lunebellec** [comment]
so this header is now part of our awesome template https://github.com/brainhack-proceedings/template

Closing this issue.
